### ISSUE TITLE
market simulation questions

### ISSUE THREAD

**Issue by pabloazurduy** [pabloazurduy/vrp-wareclouds#45]
Estimados algunas preguntas:
1. Que acceptance rate tienen actualmente con el dispatcher manual basado en `clouder history`, `clouder origin geo`, solo necesito el orden de magnitud. Cómo creen que se compararía ese rate con un rate de un random distpacher (0.4/0.7 o 0.7/0.8)?
2. de la base de clouders, que % de connected rate tienen diario ? (probabilidad que un clouder se conecte un día) 
3. En promedio cuanto es lo que pagan por nodo por ruta ? (esto incluye los nodos de warehouses?), este precio por nodo, historicamente entre que valores ha variado ?
4. cuantos clouders consideran en su "base activa" o el set de clouders a los que les envían las rutas (?) ~n (orden de magnitud solamente)
muchas gracias !

**Comment by vnramirez** [comment]
Hola @pabloazurduy, qué tal?

Aquí van:

1. En general, el acceptance rate para un clouder que ya sabemos que va a una zona con regularidad, es de entre 0.8 y 0.9. Con "ya sabemos que va a una zona" me refiero a que ha tomado esa zona 2 o más veces en las últimas dos semanas, más o menos (esto te lo digo de guata, no es un criterio duro). Y para los nuevos Clouders (digamos que son random dispatchers) les estamos mostrando únicamente zonas que sean aledañas a su residencia, yo te diría que su acceptance rate es de 0.5. De nuevo, todos estos datos son muy de guata con lo que veo todos los días, no tengo respaldo estadístico de momento, porque la tecnología actual no lo loggea.
2. Para esta pregunta voy a usar un proxy. Un 40% de los Clouders registrados han tomado ruta en las últimas dos semanas. El dato duro tampoco lo tenemos.
3. No pagamos por warehouse visitado, sólo por order entregada, y esto varía por zona. Por ejemplo, en Providencia - Las Condes - Ñuñoa pagamos $1.400. En zonas intermedias como Huechuraba - Quilicura, pagamos $2.000. En zonas más alejadas como San Bernardo o Buin llegamos a pagar hasta $3.000 por pedido entregado.
4. Justo estamos cambiando nuestra estrategia. Hace 3 meses eramos muy selectivos sobre qué le mostrábamos a quién. Con el cyber tuvimos un déficit de Clouders porque habían muchas rutas, sobre todo a zonas más complicadas, así que adoptamos más un "bombardeo" (mostrarle varias rutas a muchos Clouders simultáneamente). Hoy día estamos planificando hacer Tier Lists de Clouders por zona y así mostrarle primero las rutas disponibles a los "mejores" (mejor NS y regularidad como despachadores). Hoy en día, con la estrategia de bombardeo, yo te diría que le estamos mandando correo a 100 clouders aproximadamente (habiendo 25-30 rutas en total, en promedio). Esto ha hecho que gane el más rápido en tomar ruta, lo que se aleja bastante de nuestro objetivo (que los mejores y adecuados tomen las rutas).

Ojalá te sirva! De todas maneras, escríbeme de nuevo por cualquier cosa.

**Comment by pabloazurduy** [comment]
Bacán @vnramirez , justo eso es lo que andaba buscando, principalmente para validar los supuestos de simulación. Dado que no teníamos datos para ajustar un modelo de acceptance/matching. Creo que ando cerca de los datos reales, no perfecto, pero en ordenes de magnitud creo que andamos bien. Hoy espero conversar con el profe respecto a los resultados del modelo simulado y luego les comparto el link.

**Comment by pabloazurduy** [comment]
[BTW, la presentación ;)](https://docs.google.com/presentation/d/1wQxCKdYBiTyb-pQqR_K5j9G-ThS7IeUSFuc---Ch0Ug/edit?usp=sharing)
